### PR TITLE
Set Server URL, Set Insecure

### PR DESCRIPTION
**Pull request by DJMarlow**
Add method to set custom server URL and call setInsecure() function in connection client.

### CODE REVIEW

**Comment by TomWFox** [comment]
Hi thanks for the PR.

As you may have seen in the readme we have retired this project due to lack of contribution, however we are open to having a new maintainer take over. Would you be interested/able to do that?

**Comment by DJMarlow** [comment]
Good morning Tom,
I would be happy to take over.  I modified the current arduino parse library to work with an esp8266 project of mine, and I wanted to make sure I contributed my work in getting my IoT project functional.
I'm new to GitHub, but happy to learn.  Let me know what you need from me to take over.
Thanks,
Derrick
    On Tuesday, February 11, 2020, 10:59:15 AM PST, Tom Fox <notifications@github.com> wrote:  
 
 
Hi thanks for the PR.

As you may have seen in the readme we have retired this project due to lack of contribution, however we are open to having a new maintainer take over. Would you be interested/able to do that?

**Comment by TomWFox** [comment]
Great to hear. Usually we would escalate permissions gradually as we gain trust in the contributor and they bring value to the project. However, in this case as there are no existing maintainers it makes more difficult to onboard new contributors so I'll talk to the other members of the core team to decide the best way to proceed.

**Comment by acinader** [comment]
why insecure?

**Comment by DJMarlow** [comment]
> why insecure?

The WiFiClientSecure object wont connect unless the host fingerprint is provided OR setInscure is called.

The client.setFingerprint() can be called before connecting, and a ParseClient::setHostFingerprint could be added as well.  The caveat is that the fingerprint may change without warning, breaking the API functionality...

Thoughts?

**Comment by acinader** [comment]
the only thought i have is: ssl should always be used in 2020.  I'm assuming that this turns off ssl

having said that, if its the only solution (assuming i'm even on the right trail here), then so be it lets merge it.  just asking to make sure.

**Comment by DJMarlow** [comment]
> the only thought i have is: ssl should always be used in 2020. I'm assuming that this turns off ssl
> 
> having said that, if its the only solution (assuming i'm even on the right trail here), then so be it lets merge it. just asking to make sure.

I agree with the need for SSL.

I just tested adding ParseClient::setHostFingerprint("FINGERPRINT HERE"), and it functions well.

We could also add ParseClient::setClientInsecure(true) to call client.setInsecure()

These would expose the configuration to the IDE to support either option.

This is probably a better approach?

**Comment by acinader** [comment]
if the fingerprint is reliable, then certainly use that. 

exposing both also seems fine.

**Pull request closed without merging**
